### Regression linéaire multiple


In [11]:
#import your libraries
import numpy as np
import pandas as pa

import matplotlib.pyplot as plt 
%matplotlib inline 

from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
#load data 
prices = pa.read_csv("data/price_availability.csv", sep=";")
listings = pa.read_csv("data/listings_final.csv", sep=";")
listings = listings.drop(589)  
print("Data loaded.")

Data loaded.


In [13]:
#define input X and output Y
X = listings.loc[:, ["listing_id", "person_capacity", "bedrooms", "bathrooms" ]]
Y = []
print(X,Y)

     listing_id  person_capacity  bedrooms  bathrooms
0      28581061                1         1        2.0
1        661961                2         1        1.0
2       1261705                1         1        1.0
3       1318834                3         2        1.0
4       1677091                2         1        1.0
..          ...              ...       ...        ...
995    28335197                2         0        1.0
996    28583013                3         1        1.0
997    28628316                4         1        1.0
998    28792796                6         2        1.5
999    28682896                2         1        1.0

[999 rows x 4 columns] []


In [14]:
#price vector
for i, row in X.iterrows():
    y = 0
    ID = int(row["listing_id"])
    subset = prices[prices["listing_id"] == ID]
    y = subset["local_price"].mean()
    Y.append(y)

#convert into numpy array
Y = np.asarray(Y)

print(Y)

[  45.94845361   44.47368421   49.          165.           69.77443609
   80.56363636   61.10909091  213.32460733  174.02849741  169.
  183.0848329   297.76315789  170.           49.95275591   71.13740458
  160.          409.54887218   35.06887755   62.13533835  107.37402597
  358.12121212  115.          106.71428571   76.06896552  302.
   36.58961039   65.48484848  153.25         75.8762089   284.35356201
  219.5037594   113.53383459   93.57142857  151.07915567  300.
  109.96240602   59.07772021  101.37984496   67.20833333   60.74093264
   38.           92.           66.21204188   79.68041237   90.09819121
  170.          115.7544757   283.76115486  144.74424552  347.67015707
  115.          105.          154.65384615  380.           44.16569201
  233.69170984  147.96623377  105.          163.47286822  190.
  180.95287958  128.8630491   163.28571429   94.           94.97619048
  218.96373057  234.89460154  300.78640777   62.           59.02349869
   80.24479167   53.           92.    

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((699, 4), (699,), (300, 4), (300,))

Trainning

In [16]:
regr = linear_model.LinearRegression()
regr.fit(X_train.values, y_train)

LinearRegression()

In [17]:
#what do you think about the results ?
print('Coefficients beta_j : \n', regr.coef_)
print('Coefficients INTERCEPT beta_0 : \n', regr.intercept_)

Coefficients beta_j : 
 [2.47834609e-06 3.23451085e+01 1.43887639e+01 7.75318453e+01]
Coefficients INTERCEPT beta_0 : 
 -79.79953133672868


### Model validation

In [18]:
X_test

listing_id  person_capacity  bedrooms  bathrooms
453    14992207                2         1        1.0
794    24564156                2         1        1.0
209     3452604                2         0        1.0
309     8243908                1         1        1.0
741    23233753                5         2        1.0
..          ...              ...       ...        ...
314     8525469                8         3        2.5
404    12976143                7         3        2.0
7       5662637                2         1        1.0
155     2158913                2         0        1.0
810    24766158                9         4        3.0

[300 rows x 4 columns]

In [19]:
y_test

array([  79.81038961,  125.        ,   95.45333333,   29.        ,
         82.5883905 ,  123.63829787,  360.        ,  130.        ,
        450.        ,  164.845953  ,   68.35142119,  294.18181818,
         68.08247423,   51.01595745,  170.30548303,   80.24479167,
         73.78249337,  195.        ,  375.0268714 ,  834.96124031,
        850.65633075,   89.        ,  650.        ,   63.38219895,
         83.        ,  190.        ,  202.23514212,   96.6056701 ,
        108.95026178,   50.        ,   28.31937173,  195.        ,
         93.70234987,  474.14258189,  450.        ,  517.0984456 ,
         83.37730871,  395.        ,   79.        ,  129.17493473,
        135.11227154,   51.52785146,  117.22572178,  260.        ,
        618.        ,   42.        ,  180.        ,  160.        ,
        179.67315175,   40.0025641 ,   80.984375  ,  116.09947644,
        429.28645833,   76.06896552,  219.5037594 ,  459.71391076,
        183.0848329 ,  204.39276486,  161.5503876 ,  131.     

In [ ]:
#compute y_pred
Y_pred = regr.predict(X_test)
len(Y_pred)

In [21]:
Y_pred

array([113.96717254, 137.68977495,  70.97927863,  64.89744358,
       245.81666527, 170.4788043 , 561.0179989 , 106.9418946 ,
       383.27653253, 233.75294378, 162.22364018, 612.08191179,
       159.32890963, 251.58804631, 118.1210298 ,  78.77744367,
       124.68010657, 194.48881109, 434.03826221, 790.83639952,
       586.83384388, 171.78524314, 221.95377062, 128.08854869,
       128.62279089, 175.3227481 , 121.6775822 , 154.48438242,
       156.15601944,  69.49655503,  92.87029058, 216.30267547,
       112.59683353, 754.37308581, 455.87067501, 287.66991756,
        67.79340934, 359.1764754 , 129.24823819, 214.40674172,
       169.73401224,  60.79931294, 209.06281997, 236.21743727,
       320.30632589, 123.62663053,  77.81376409, 198.81582295,
        78.94863791, 145.15976783, 127.84082014, 152.26503044,
       224.58908772,  69.26447379, 298.66775754, 164.39766518,
       214.32584501, 185.47409534, 218.11339591, 119.70295068,
        77.9772229 , 169.06272431, 141.63669477, 263.08

In [22]:
y_test

array([  79.81038961,  125.        ,   95.45333333,   29.        ,
         82.5883905 ,  123.63829787,  360.        ,  130.        ,
        450.        ,  164.845953  ,   68.35142119,  294.18181818,
         68.08247423,   51.01595745,  170.30548303,   80.24479167,
         73.78249337,  195.        ,  375.0268714 ,  834.96124031,
        850.65633075,   89.        ,  650.        ,   63.38219895,
         83.        ,  190.        ,  202.23514212,   96.6056701 ,
        108.95026178,   50.        ,   28.31937173,  195.        ,
         93.70234987,  474.14258189,  450.        ,  517.0984456 ,
         83.37730871,  395.        ,   79.        ,  129.17493473,
        135.11227154,   51.52785146,  117.22572178,  260.        ,
        618.        ,   42.        ,  180.        ,  160.        ,
        179.67315175,   40.0025641 ,   80.984375  ,  116.09947644,
        429.28645833,   76.06896552,  219.5037594 ,  459.71391076,
        183.0848329 ,  204.39276486,  161.5503876 ,  131.     

In [25]:
#display the least squares error on the training set as well as the R2
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, Y_pred))
# Coefficient of determination R2
print('Variance score: %.2f' % r2_score(y_test, Y_pred))


#compute the RMSE for more intuitive results
np.sqrt(19631.83)


Mean squared error: 19631.83
Variance score: 0.42


140.1136324559463